apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dito-app

namePrefix: production-

commonLabels:
  environment: production
  app.kubernetes.io/version: production

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: dito-api-secrets
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: dito-db-password-production

images:
  - name: southamerica-east1-docker.pkg.dev/PROJECT/dito-api-staging/dito-api
    newName: southamerica-east1-docker.pkg.dev/PROJECT/dito-api-production/dito-api
    newTag: v1.0.0
