apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: groove
  namespace: dito-app
  labels:
    app.kubernetes.io/name: groove
    app.kubernetes.io/component: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ingressClassName: traefik
  rules:
    - host: groove.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dito-api
                port:
                  name: http
