apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: infra

  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.5
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
          keep: true
        prometheus:
          enabled: false
        webhook:
          timeoutSeconds: 10

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  revisionHistoryLimit: 3
