apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuers-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-issuers
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infra

  source:
    repoURL: https://github.com/nikolastsdev/dito-devops-challenge
    targetRevision: main
    path: manifests/infra/cluster-issuers

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  revisionHistoryLimit: 3
