apiVersion: apps/v1
kind: Deployment
metadata:
  name: dito-api
  namespace: dito-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: dito-api
          env:
            - name: NODE_ENV
              value: staging
