apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dito-app

labels:
  - pairs:
      environment: staging
      app.kubernetes.io/version: staging
    includeSelectors: false

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: southamerica-east1-docker.pkg.dev/PROJECT/dito-api-staging/dito-api
    newName: southamerica-east1-docker.pkg.dev/dito-staging/dito-api-staging/dito-api
    newTag: staging-latest
